<?php
return [
    [1, 'AF', 'Afghanistan'],
    [2, 'AX', 'Aland Islands'],
    [3, 'AL', 'Albania'],
    [4, 'DZ', 'Algeria'],
    [5, 'AS', 'American Samoa'],
    [6, 'AD', 'Andorra'],
    [7, 'AO', 'Angola'],
    [8, 'AI', 'Anguilla'],
    [9, 'AQ', 'Antarctica'],
    [10, 'AG', 'Antigua and Barbuda'],
    [11, 'AR', 'Argentina'],
    [12, 'AM', 'Armenia'],
    [13, 'AW', 'Aruba'],
    [14, 'AU', 'Australia'],
    [15, 'AT', 'Austria'],
    [16, 'AZ', 'Azerbaijan'],
    [17, 'BS', 'Bahamas'],
    [18, 'BH', 'Bahrain'],
    [19, 'BD', 'Bangladesh'],
    [20, 'BB', 'Barbados'],
    [21, 'BY', 'Belarus'],
    [22, 'BE', 'Belgium'],
    [23, 'BZ', 'Belize'],
    [24, 'BJ', 'Benin'],
    [25, 'BM', 'Bermuda'],
    [26, 'BT', 'Bhutan'],
    [27, 'BO', 'Bolivia'],
    [28, 'BQ', 'Bonaire, Sint Eustatius and Saba'],
    [29, 'BA', 'Bosnia and Herzegovina'],
    [30, 'BW', 'Botswana'],
    [31, 'BV', 'Bouvet Island'],
    [32, 'BR', 'Brazil'],
    [33, 'IO', 'British Indian Ocean Territory'],
    [34, 'BN', 'Brunei Darussalam'],
    [35, 'BG', 'Bulgaria'],
    [36, 'BF', 'Burkina Faso'],
    [37, 'BI', 'Burundi'],
    [38, 'KH', 'Cambodia'],
    [39, 'CM', 'Cameroon'],
    [40, 'CA', 'Canada'],
    [41, 'CV', 'Cape Verde'],
    [42, 'KY', 'Cayman Islands'],
    [43, 'CF', 'Central African Republic'],
    [44, 'TD', 'Chad'],
    [45, 'CL', 'Chile'],
    [46, 'CN', 'China'],
    [47, 'CX', 'Christmas Island'],
    [48, 'CC', 'Cocos (Keeling) Islands'],
    [49, 'CO', 'Colombia'],
    [50, 'KM', 'Comoros'],
    [51, 'CG', 'Congo'],
    [52, 'CD', 'Congo, Democratic Republic of the Congo'],
    [53, 'CK', 'Cook Islands'],
    [54, 'CR', 'Costa Rica'],
    [55, 'CI', 'Cote D\'Ivoire'],
    [56, 'HR', 'Croatia'],
    [57, 'CU', 'Cuba'],
    [58, 'CW', 'Curacao'],
    [59, 'CY', 'Cyprus'],
    [60, 'CZ', 'Czech Republic'],
    [61, 'DK', 'Denmark'],
    [62, 'DJ', 'Djibouti'],
    [63, 'DM', 'Dominica'],
    [64, 'DO', 'Dominican Republic'],
    [65, 'EC', 'Ecuador'],
    [66, 'EG', 'Egypt'],
    [67, 'SV', 'El Salvador'],
    [68, 'GQ', 'Equatorial Guinea'],
    [69, 'ER', 'Eritrea'],
    [70, 'EE', 'Estonia'],
    [71, 'ET', 'Ethiopia'],
    [72, 'FK', 'Falkland Islands (Malvinas)'],
    [73, 'FO', 'Faroe Islands'],
    [74, 'FJ', 'Fiji'],
    [75, 'FI', 'Finland'],
    [76, 'FR', 'France'],
    [77, 'GF', 'French Guiana'],
    [78, 'PF', 'French Polynesia'],
    [79, 'TF', 'French Southern Territories'],
    [80, 'GA', 'Gabon'],
    [81, 'GM', 'Gambia'],
    [82, 'GE', 'Georgia'],
    [83, 'DE', 'Germany'],
    [84, 'GH', 'Ghana'],
    [85, 'GI', 'Gibraltar'],
    [86, 'GR', 'Greece'],
    [87, 'GL', 'Greenland'],
    [88, 'GD', 'Grenada'],
    [89, 'GP', 'Guadeloupe'],
    [90, 'GU', 'Guam'],
    [91, 'GT', 'Guatemala'],
    [92, 'GG', 'Guernsey'],
    [93, 'GN', 'Guinea'],
    [94, 'GW', 'Guinea-Bissau'],
    [95, 'GY', 'Guyana'],
    [96, 'HT', 'Haiti'],
    [97, 'HM', 'Heard Island and Mcdonald Islands'],
    [98, 'VA', 'Holy See (Vatican City State)'],
    [99, 'HN', 'Honduras'],
    [100, 'HK', 'Hong Kong'],
    [101, 'HU', 'Hungary'],
    [102, 'IS', 'Iceland'],
    [103, 'IN', 'India'],
    [104, 'ID', 'Indonesia'],
    [105, 'IR', 'Iran, Islamic Republic of'],
    [106, 'IQ', 'Iraq'],
    [107, 'IE', 'Ireland'],
    [108, 'IM', 'Isle of Man'],
    [109, 'IL', 'Israel'],
    [110, 'IT', 'Italy'],
    [111, 'JM', 'Jamaica'],
    [112, 'JP', 'Japan'],
    [113, 'JE', 'Jersey'],
    [114, 'JO', 'Jordan'],
    [115, 'KZ', 'Kazakhstan'],
    [116, 'KE', 'Kenya'],
    [117, 'KI', 'Kiribati'],
    [118, 'KP', 'Korea, Democratic People\'s Republic of'],
    [119, 'KR', 'Korea, Republic of'],
    [120, 'KW', 'Kuwait'],
    [121, 'KG', 'Kyrgyzstan'],
    [122, 'LA', 'Lao People\'s Democratic Republic'],
    [123, 'LV', 'Latvia'],
    [124, 'LB', 'Lebanon'],
    [125, 'LS', 'Lesotho'],
    [126, 'LR', 'Liberia'],
    [127, 'LY', 'Libyan Arab Jamahiriya'],
    [128, 'LI', 'Liechtenstein'],
    [129, 'LT', 'Lithuania'],
    [130, 'LU', 'Luxembourg'],
    [131, 'MO', 'Macao'],
    [132, 'MK', 'Macedonia, the Former Yugoslav Republic of'],
    [133, 'MG', 'Madagascar'],
    [134, 'MW', 'Malawi'],
    [135, 'MY', 'Malaysia'],
    [136, 'MV', 'Maldives'],
    [137, 'ML', 'Mali'],
    [138, 'MT', 'Malta'],
    [139, 'MH', 'Marshall Islands'],
    [140, 'MQ', 'Martinique'],
    [141, 'MR', 'Mauritania'],
    [142, 'MU', 'Mauritius'],
    [143, 'YT', 'Mayotte'],
    [144, 'MX', 'Mexico'],
    [145, 'FM', 'Micronesia, Federated States of'],
    [146, 'MD', 'Moldova, Republic of'],
    [147, 'MC', 'Monaco'],
    [148, 'MN', 'Mongolia'],
    [149, 'ME', 'Montenegro'],
    [150, 'MS', 'Montserrat'],
    [151, 'MA', 'Morocco'],
    [152, 'MZ', 'Mozambique'],
    [153, 'MM', 'Myanmar'],
    [154, 'NA', 'Namibia'],
    [155, 'NR', 'Nauru'],
    [156, 'NP', 'Nepal'],
    [157, 'NL', 'Netherlands'],
    [158, 'AN', 'Netherlands Antilles'],
    [159, 'NC', 'New Caledonia'],
    [160, 'NZ', 'New Zealand'],
    [161, 'NI', 'Nicaragua'],
    [162, 'NE', 'Niger'],
    [163, 'NG', 'Nigeria'],
    [164, 'NU', 'Niue'],
    [165, 'NF', 'Norfolk Island'],
    [166, 'MP', 'Northern Mariana Islands'],
    [167, 'NO', 'Norway'],
    [168, 'OM', 'Oman'],
    [169, 'PK', 'Pakistan'],
    [170, 'PW', 'Palau'],
    [171, 'PS', 'Palestinian Territory, Occupied'],
    [172, 'PA', 'Panama'],
    [173, 'PG', 'Papua New Guinea'],
    [174, 'PY', 'Paraguay'],
    [175, 'PE', 'Peru'],
    [176, 'PH', 'Philippines'],
    [177, 'PN', 'Pitcairn'],
    [178, 'PL', 'Poland'],
    [179, 'PT', 'Portugal'],
    [180, 'PR', 'Puerto Rico'],
    [181, 'QA', 'Qatar'],
    [182, 'RE', 'Reunion'],
    [183, 'RO', 'Romania'],
    [184, 'RU', 'Russian Federation'],
    [185, 'RW', 'Rwanda'],
    [186, 'BL', 'Saint Barthelemy'],
    [187, 'SH', 'Saint Helena'],
    [188, 'KN', 'Saint Kitts and Nevis'],
    [189, 'LC', 'Saint Lucia'],
    [190, 'MF', 'Saint Martin'],
    [191, 'PM', 'Saint Pierre and Miquelon'],
    [192, 'VC', 'Saint Vincent and the Grenadines'],
    [193, 'WS', 'Samoa'],
    [194, 'SM', 'San Marino'],
    [195, 'ST', 'Sao Tome and Principe'],
    [196, 'SA', 'Saudi Arabia'],
    [197, 'SN', 'Senegal'],
    [198, 'RS', 'Serbia'],
    [199, 'SC', 'Seychelles'],
    [200, 'SL', 'Sierra Leone'],
    [201, 'SG', 'Singapore'],
    [202, 'SX', 'Sint Maarten'],
    [203, 'SK', 'Slovakia'],
    [204, 'SI', 'Slovenia'],
    [205, 'SB', 'Solomon Islands'],
    [206, 'SO', 'Somalia'],
    [207, 'ZA', 'South Africa'],
    [208, 'GS', 'South Georgia and the South Sandwich Islands'],
    [209, 'SS', 'South Sudan'],
    [210, 'ES', 'Spain'],
    [211, 'LK', 'Sri Lanka'],
    [212, 'SD', 'Sudan'],
    [213, 'SR', 'Suriname'],
    [214, 'SJ', 'Svalbard and Jan Mayen'],
    [215, 'SZ', 'Swaziland'],
    [216, 'SE', 'Sweden'],
    [217, 'CH', 'Switzerland'],
    [218, 'SY', 'Syrian Arab Republic'],
    [219, 'TW', 'Taiwan, Province of China'],
    [220, 'TJ', 'Tajikistan'],
    [221, 'TZ', 'Tanzania, United Republic of'],
    [222, 'TH', 'Thailand'],
    [223, 'TL', 'Timor-Leste'],
    [224, 'TG', 'Togo'],
    [225, 'TK', 'Tokelau'],
    [226, 'TO', 'Tonga'],
    [227, 'TT', 'Trinidad and Tobago'],
    [228, 'TN', 'Tunisia'],
    [229, 'TR', 'Turkey'],
    [230, 'TM', 'Turkmenistan'],
    [231, 'TC', 'Turks and Caicos Islands'],
    [232, 'TV', 'Tuvalu'],
    [233, 'UG', 'Uganda'],
    [234, 'UA', 'Ukraine'],
    [235, 'AE', 'United Arab Emirates'],
    [236, 'GB', 'United Kingdom'],
    [237, 'US', 'United States'],
    [238, 'UM', 'United States Minor Outlying Islands'],
    [239, 'UY', 'Uruguay'],
    [240, 'UZ', 'Uzbekistan'],
    [241, 'VU', 'Vanuatu'],
    [242, 'VE', 'Venezuela'],
    [243, 'VN', 'Viet Nam'],
    [244, 'VG', 'Virgin Islands, British'],
    [245, 'VI', 'Virgin Islands, U.S.'],
    [246, 'WF', 'Wallis and Futuna'],
    [247, 'EH', 'Western Sahara'],
    [248, 'YE', 'Yemen'],
    [249, 'ZM', 'Zambia'],
    [250, 'ZW', 'Zimbabwe'],
];